---
- name: This sets up an httpd webserver
  hosts: RS
  vars_files:
    - "vars.yaml"
  tasks:
  - name: Install the httpd apps
    yum: name={{ package }}
  - name: start the httpd service
    service: name={{ service }} state=started
  - name: Ansible prompt example.
    debug:
      msg: "{{ myname }}"
...
