---
- name: Installing httpd server
  hosts: web1
  tasks:
  - name: Installing httpd server
    yum: name=httpd state=present
  - name: Starting service
    service: name=httpd state=started enabled=yes
