---
# tasks file for web
  - name: Install the httpd apps
    yum: name={{ package }}
    when:
      - ansible_distribution == "CentOS"
  - name: start the httpd service
    service: name={{ service }} state=started
  - name: Copy Site Files
    template: src=index.j2 dest=/var/www/html/index.html
  - name: Copy Site Files
    template: src=httpd.j2 dest=/etc/httpd/conf/httpd.conf
    notify:
      - Restart Apache
