---
- name: This sets up an httpd webserver
  hosts: web
  vars_files:
    - "vars.yaml"

  tasks:
  - name: Install the httpd apps
    yum: name={{ package }}
  - name: start the httpd service
    service: name={{ service }} state=started
  - debug:
      msg: My Name is  {{ myname }}
